### ISSUE TITLE
length = 20480,what this hp mean?

### ISSUE THREAD

**Issue by switchzts** [dhgrs/pytorch-UniWaveNet#1]
Does it represent the minimum length of each speech? Why do you want to send each segment of speech into training? Is it the reason for memory resources?

**Comment by dhgrs** [comment]
The length of training audio is exactly same as `length` in `params.py`. If audio in dataset is shorter than `length` then apply padding and longer then apply trimming. The code is here.
https://github.com/dhgrs/pytorch-UniWaveNet/blob/4156ef271307226f17493e2d0bb899e6da07e0c0/utils.py#L37-L43

The reason is to make a mini batch. Samples in a mini batch must be same size.

**Comment by switchzts** [comment]
@dhgrs Thanks for the reply~, 
What happens when I adjust this parameter? Should it be as close as possible to the length of most of the original audio? If I turn this parameter down, will it make synthesized audio to  meaningless pronunciation?

**Comment by dhgrs** [comment]
In [original Parallel WaveNet paper](http://proceedings.mlr.press/v80/oord18a.html), they say that each audio contains only 7680 samples and it is sufficient to train (Parallel) WaveNet.
But Uni-WaveNet uses STFT for calculating loss and its largest window size is 4096. So I think 7680 is too small to train Uni-WaveNet.

Then I agree that it should be as close as possible to the length of most of the original audio. And I think setting length less than about 10000 makes the results worse.

**Comment by switchzts** [comment]
@dhgrs OK~ Thanks~ BTW, how many steps and loss do you train to get generated samples in README.md?

**Comment by dhgrs** [comment]
I generated samples in README with 300k iterations, log_loss=12.390, magnitude_loss=1.631 and power_loss=9.087. I'm still running the training and now 450k iterations. The quality got a bit better.
FYI, we can recognize what generated samples pronounce about 30k iterations.
