### ISSUE TITLE
Does it compatible to Integrate with Tacotron 2 ?

### ISSUE THREAD

**Issue by rishikksh20** [dhgrs/pytorch-UniWaveNet#4]
Hello, nice implementation but I am curious that weather this Wavenet easily integrate with Tacotron-2 (https://github.com/Rayhane-mamah/Tacotron-2). And also what is the synthesis speed of this Wavenet , Is it in real time ?

**Comment by dhgrs** [comment]
I designed hyper parameters as same as that repository so maybe can integrate easily. But improving generated audio quality is higher priority in my plan. So if you want to try it soon, please send a PR!

I use 1080Ti and it can generate over 3 seconds audio per second. It is 3x faster. And I time it in evaluating phase so it includes calculating loss and others. So it can be faster.

**Comment by dhgrs** [comment]
@rishikksh20 Sorry, I thought you mentioned about [Tacotron2 implemented by NVIDIA](https://github.com/NVIDIA/tacotron2). My Uni-WaveNet implementation is not based on Rayhane-mamah's but NVIDIA's. Sorry for the confusion

**Comment by rishikksh20** [comment]
@dhgrs no problem I read your README from there I got that.
