### ISSUE TITLE
Why iterating the wavenet_list from index 1?

### ISSUE THREAD

**Issue by nanma** [dhgrs/pytorch-UniWaveNet#5]
In the `forward()` method of class `UniWaveNet` in `net.py`,  the code below iterate the wavenet_list from index 1, so the wavenet_list[0] will be skipped.
```
    for i, wavenet in enumerate(self.wavenet_list[1:]):
```
I'm wondering why skipping the first layer of wavenet_list?

**Comment by dhgrs** [comment]
It's a stupid mistake. It should be `for i, wavenet in enumerate(self.wavenet_list):`. I don't know why I wrote such code... Thank you for pointing out!

Could you send PR? Or I will fix it if it is hard.

**Comment by nanma** [comment]
My pleasure. A pr has been sent.
